/**
 * fetch-fonts.mjs — self-host the site fonts.
 *
 * Fetches the Google Fonts CSS (with a modern Chrome UA so woff2 URLs are
 * returned), downloads each woff2 into public/fonts/, and writes a
 * self-contained @font-face stylesheet to src/styles/fonts.css.
 *
 * Usage:  node scripts/fetch-fonts.mjs
 * Idempotent: re-running overwrites public/fonts/*.woff2 and fonts.css.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const FONT_DIR = join(root, "public", "fonts");
const OUT_CSS = join(root, "src", "styles", "fonts.css");

const FAMILIES =
  "family=Space+Grotesk:wght@400;500;600;700" +
  "&family=Inter:wght@300;400;500;600;700" +
  "&family=Noto+Sans+Ethiopic:wght@400;500;600;700;800";
const CSS_URL = `https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`;

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

const slug = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

async function main() {
  const res = await fetch(CSS_URL, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`CSS fetch failed: ${res.status} ${res.statusText}`);
  const css = await res.text();

  const blocks = [...css.matchAll(/@font-face\s*{([^}]*)}/g)].map((m) => m[1]);
  if (blocks.length === 0) throw new Error("No @font-face blocks found in CSS.");

  mkdirSync(FONT_DIR, { recursive: true });
  const out = [];

  for (const block of blocks) {
    const get = (prop) => {
      const m = block.match(new RegExp(`${prop}:\\s*([^;]+);`));
      return m ? m[1].trim().replace(/^['"]|['"]$/g, "") : null;
    };
    const family = get("font-family");
    const weight = get("font-weight") || "400";
    const style = get("font-style") || "normal";
    const url = get("src")?.match(/url\((https:[^)]+)\)/)?.[1];
    const unicodeRange = get("unicode-range") || null;
    if (!family || !url) continue;

    // Google's per-subset woff2 files end with a unique hash segment.
    const subsetId = url.split("/").pop().replace(/\.woff2$/, "");
    const file = `${slug(family)}-${weight}${style === "italic" ? "i" : ""}-${subsetId}.woff2`;
    const filePath = join(FONT_DIR, file);

    const f = await fetch(url);
    if (!f.ok) throw new Error(`woff2 fetch failed (${file}): ${f.status}`);
    const buf = Buffer.from(await f.arrayBuffer());
    writeFileSync(filePath, buf);

    out.push(
      `@font-face {\n` +
        `  font-family: "${family}";\n` +
        `  font-style: ${style};\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        (unicodeRange ? `  unicode-range: ${unicodeRange};\n` : ``) +
        `  src: url("/fonts/${file}") format("woff2");\n` +
        `}\n`
    );
  }

  const header =
    `/* ============================================================\n` +
    `   SELF-HOSTED FONTS — generated by scripts/fetch-fonts.mjs\n` +
    `   Re-run "node scripts/fetch-fonts.mjs" to refresh.\n` +
    `   ============================================================ */\n`;
  writeFileSync(OUT_CSS, header + "\n" + out.join("\n"));
  console.log(
    `OK — wrote ${out.length} @font-face rules to ${OUT_CSS}\n` +
      `      and ${blocks.length} css blocks, fonts in public/fonts/`
  );
}

main().catch((err) => {
  console.error("Font self-hosting failed:", err.message);
  console.error(
    "Network access to fonts.googleapis.com appears unavailable.\n" +
      "Fallback: keep system-font stacks in global.css (works offline)."
  );
  process.exit(1);
});
